version: 1.0.{build}
branches:
  only:
  - main
skip_tags: true
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
only_commits:
  message: /\[ci\]/
skip_commits:
  files:
    - docu/
    - '**/*.md'
    - '*.txt'
    - appveyor.yml
    - LICENSE.txt
    - '.gitignor'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a DarkModeActivator-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\DarkModeActivator\bin\Release\net8.0\*.*
artifacts:
- path: DarkModeActivator-%APPVEYOR_BUILD_VERSION%.zip
  name: DarkModeActivator
deploy:
- provider: GitHub
  auth_token:
    secure: LprsSeYQlaK3+EorcwvQ13w66LtJEPixbWnpL54ucz/8u7kCC7y2mkJOj4aOFikc
  artifact: DarkModeActivator
  description: "`DarkModeActivator-%APPVEYOR_BUILD_VERSION%.zip` contain the application (*.exe) and some essential dependencies. \n\n#### Last commit message\n%APPVEYOR_REPO_COMMIT_MESSAGE%"